/// Web-specific database adapter using SharedPreferences.
///
/// This library provides a database adapter for web platforms that uses
/// SharedPreferences for persistent storage. Data is stored as JSON in
/// browser local storage.
library;

import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:bluepills/models/medication.dart';
import 'package:bluepills/models/medication_log.dart';
import 'database_adapter.dart';

/// Database adapter implementation for web platforms.
///
/// Uses SharedPreferences (browser local storage) to store medications
/// as JSON. This adapter is automatically selected when running on web
/// platforms.
///
/// All medications are stored in a single JSON array under the key
/// 'medications'. IDs are generated by finding the maximum existing ID
/// and incrementing it.
class WebDatabaseAdapter extends DatabaseAdapter {
  late SharedPreferences _prefs;

  @override
  Future<void> init() async {
    _prefs = await SharedPreferences.getInstance();
  }

  @override
  Future<int> insertMedication(Medication medication) async {
    final List<Map<String, dynamic>> medications = _getFromLocalStorage();
    int newId = 1;
    if (medications.isNotEmpty) {
      newId =
          medications
              .map<int>((m) => m['id'] as int)
              .reduce((a, b) => a > b ? a : b) +
          1;
    }
    medication.id = newId;
    final Map<String, dynamic> medicationMap = medication.toMap();
    medications.add(medicationMap);
    _saveToLocalStorage(medications);
    return newId;
  }

  @override
  Future<List<Medication>> getMedications() async {
    final List<Map<String, dynamic>> medications = _getFromLocalStorage();
    return medications.map((map) => Medication.fromMap(map)).toList();
  }

  @override
  Future<int> updateMedication(Medication medication) async {
    final List<Map<String, dynamic>> medications = _getFromLocalStorage();
    int index = medications.indexWhere((m) => m['id'] == medication.id);
    if (index >= 0) {
      medications[index] = medication.toMap();
      _saveToLocalStorage(medications);
      return 1;
    }
    return 0;
  }

  @override
  Future<int> deleteMedication(int id) async {
    final List<Map<String, dynamic>> medications = _getFromLocalStorage();
    int initialLength = medications.length;
    medications.removeWhere((m) => m['id'] == id);
    _saveToLocalStorage(medications);
    return initialLength - medications.length;
  }

  void _saveToLocalStorage(List<Map<String, dynamic>> medications) {
    final String data = jsonEncode(medications);
    _prefs.setString('medications', data);
  }

  List<Map<String, dynamic>> _getFromLocalStorage() {
    final String? data = _prefs.getString('medications');
    if (data != null && data.isNotEmpty) {
      final List<dynamic> decoded = jsonDecode(data);
      return decoded.map((item) => Map<String, dynamic>.from(item)).toList();
    }
    return [];
  }

  @override
  Future<int> insertMedicationLog(MedicationLog log) async {
    // Not implemented for web
    return 0;
  }

  @override
  Future<List<MedicationLog>> getMedicationLogs(int medicationId) async {
    // Not implemented for web
    return [];
  }

  @override
  Future<Medication?> getMedication(int id) async {
    // Not implemented for web
    return null;
  }

  @override
  Future<DateTime?> getLastTakenTime(int medicationId) async {
    // Not implemented for web
    return null;
  }
}
