name: Bug Report
description: File a bug report to help us improve BluePills
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true

  - type: dropdown
    attributes:
      label: Platform
      description: Which platform(s) are you experiencing this bug on?
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: input
    attributes:
      label: App Version
      description: What version of BluePills are you running?
      placeholder: "e.g., v1.0.0"
    validations:
      required: true

  - type: input
    attributes:
      label: Device/OS Version
      description: What device and OS version are you using?
      placeholder: "e.g., Pixel 7, Android 14 or Chrome 120, Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: What is currently happening? A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should happen instead? A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Sync Mode
      description: Are you using BlueSky sync or local storage only?
      options:
        - Local storage only
        - BlueSky sync enabled
        - Not applicable
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error Logs
      description: If applicable, add any error messages or logs you're seeing.
      render: text

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.