blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/your-username/BluePills/discussions
    about: For questions, ideas, and community discussions
  
  - name: 🔒 Security Issues
    url: https://github.com/your-username/BluePills/security/advisories/new
    about: For reporting security vulnerabilities (private)
    
  - name: 📚 Documentation
    url: https://github.com/your-username/BluePills/wiki
    about: Check our documentation and guides