name: Feature Request
description: Suggest an idea for BluePills
title: "[Feature]: "
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 💡

  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a feature request already exists.
      options:
      - label: I have searched the existing issues and feature requests
        required: true

  - type: dropdown
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Medication Management
        - Notifications & Reminders
        - BlueSky/AT Protocol Integration
        - User Interface
        - Data Import/Export
        - Accessibility
        - Security & Privacy
        - Cross-Platform Support
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Important for usability
        - Critical - Blocking current workflow
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Affected Platforms
      description: Which platforms should this feature support?
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - Linux
        - macOS
        - Windows
        - All platforms
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.

  - type: checkboxes
    attributes:
      label: Implementation
      description: Are you interested in contributing to this feature?
      options:
      - label: I would be willing to submit a pull request for this feature
      - label: I would be willing to help with testing
      - label: I would be willing to help with documentation