// GENERATED CODE - DO NOT MODIFY BY HAND

/// Generated JSON serialization code for [AppConfig].
///
/// This file is automatically generated by json_serializable.
/// Any manual changes to this file will be lost when the code is regenerated.
/// To regenerate, run: flutter pub run build_runner build
part of 'app_config.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

AppConfig _$AppConfigFromJson(Map<String, dynamic> json) => AppConfig(
  syncEnabled: json['syncEnabled'] as bool? ?? false,
  blueskyHandle: json['blueskyHandle'] as String?,
  pdsUrl: json['pdsUrl'] as String?,
  lastSyncTime: json['lastSyncTime'] == null
      ? null
      : DateTime.parse(json['lastSyncTime'] as String),
  syncMode:
      $enumDecodeNullable(_$SyncModeEnumMap, json['syncMode']) ??
      SyncMode.localOnly,
);

Map<String, dynamic> _$AppConfigToJson(AppConfig instance) => <String, dynamic>{
  'syncEnabled': instance.syncEnabled,
  'blueskyHandle': instance.blueskyHandle,
  'pdsUrl': instance.pdsUrl,
  'lastSyncTime': instance.lastSyncTime?.toIso8601String(),
  'syncMode': _$SyncModeEnumMap[instance.syncMode]!,
};

const _$SyncModeEnumMap = {
  SyncMode.localOnly: 'localOnly',
  SyncMode.syncEnabled: 'syncEnabled',
  SyncMode.syncOnly: 'syncOnly',
};
