// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'app_config.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

/// Creates an [AppConfig] instance from a JSON map.
///
/// This function is generated by json_serializable and is used internally
/// by the [AppConfig.fromJson] factory constructor to deserialize JSON data
/// into an [AppConfig] object with proper type conversion and default values.
AppConfig _$AppConfigFromJson(Map<String, dynamic> json) => AppConfig(
  syncEnabled: json['syncEnabled'] as bool? ?? false,
  blueskyHandle: json['blueskyHandle'] as String?,
  pdsUrl: json['pdsUrl'] as String?,
  lastSyncTime: json['lastSyncTime'] == null
      ? null
      : DateTime.parse(json['lastSyncTime'] as String),
  syncMode:
      $enumDecodeNullable(_$SyncModeEnumMap, json['syncMode']) ??
      SyncMode.localOnly,
  autoRestoreEnabled: json['autoRestoreEnabled'] as bool? ?? true,
  languageCode: json['languageCode'] as String?,
);

/// Converts an [AppConfig] instance to a JSON map.
///
/// This function is generated by json_serializable and is used internally
/// by the [AppConfig.toJson] method to serialize an [AppConfig] object
/// into a JSON-compatible map for storage or transmission.
Map<String, dynamic> _$AppConfigToJson(AppConfig instance) => <String, dynamic>{
  'syncEnabled': instance.syncEnabled,
  'blueskyHandle': instance.blueskyHandle,
  'pdsUrl': instance.pdsUrl,
  'lastSyncTime': instance.lastSyncTime?.toIso8601String(),
  'syncMode': _$SyncModeEnumMap[instance.syncMode]!,
  'autoRestoreEnabled': instance.autoRestoreEnabled,
  'languageCode': instance.languageCode,
};

/// Enumeration mapping for [SyncMode] serialization.
///
/// This constant map is generated by json_serializable and provides the
/// mapping between [SyncMode] enum values and their JSON string representations
/// for proper serialization and deserialization.
const _$SyncModeEnumMap = {
  SyncMode.localOnly: 'localOnly',
  SyncMode.syncEnabled: 'syncEnabled',
  SyncMode.syncOnly: 'syncOnly',
};
